name: zuppa-ge
version: '1.0'
# synopsis:
# description:
license: ISC
author: Dino Morelli
maintainer: dino@ui3.info
copyright: 2022 Dino Morelli
category: Unclassified
extra-source-files:
- CHANGELOG.md
- .gitignore
- package.yaml
- README.md
- stack.yaml

github: dino-/zuppa-ge

ghc-options:
- -fwarn-tabs
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- BangPatterns
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NumericUnderscores
- OverloadedStrings
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections

dependencies:
- base >=3 && <5

library:
  source-dirs: src/lib
  dependencies:
  - microlens-platform
  - random

executables:
  trapped-with-hans:
    source-dirs: src/app
    main: trapped-with-hans.hs
    dependencies:
    - zuppa-ge

tests:
  zuppa-ge-test-suite:
    source-dirs: src/test
    main: Main.hs
    dependencies:
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - zuppa-ge
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
